Send alerts to ntfy topics

diff --git a/changeme b/changeme
--- a/changeme
+++ b/changeme
@@ -7,11 +7,22 @@
 #
 
 HOSTNAME=`hostname`
-MSG="$HOSTNAME UPS $1 battery needs changing NOW."
-#
-(
-   echo "$MSG"
-   echo " "
-   /sbin/apcaccess status
-) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
+NOTIFY_HOST="ntfy.sh"
+NOTIFY_TOPIC=your-own-topic
+
+haveCurl=$(which curl)
+
+if [ $? -ne 0 ]; then
+  echo "Curl is not installed or not found in path, please install curl."
+  exit 1
+fi
+
+curl \
+  -s \
+  -o /dev/null \
+  -H "Title: $HOSTNAME UPS $1 Battery Needs Replaced" \
+  -H "Priority: urgent" \
+  -H "Tags: ups" \
+  -d "$HOSTNAME UPS $1 battery requires replacement!" $NOTIFY_HOST/$NOTIFY_TOPIC
+
 exit 0
diff --git a/offbattery b/offbattery
--- a/offbattery
+++ b/offbattery
@@ -7,11 +7,22 @@
 #
 
 HOSTNAME=`hostname`
-MSG="$HOSTNAME UPS $1 Power has returned"
-#
-(
-   echo "$MSG"
-   echo " "
-   /sbin/apcaccess status
-) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
+NOTIFY_HOST="ntfy.sh"
+NOTIFY_TOPIC=your-own-topic
+
+haveCurl=$(which curl)
+
+if [ $? -ne 0 ]; then
+  echo "Curl is not installed or not found in path, please install curl."
+  exit 1
+fi
+
+curl \
+  -s \
+  -o /dev/null \
+  -H "Title: $HOSTNAME UPS $1 Power Restored" \
+  -H "Priority: default" \
+  -H "Tags: ups" \
+  -d "$HOSTNAME UPS $1 has switched back to line power" $NOTIFY_HOST/$NOTIFY_TOPIC
+
 exit 0
diff --git a/onbattery b/onbattery
--- a/onbattery
+++ b/onbattery
@@ -7,11 +7,22 @@
 #
 
 HOSTNAME=`hostname`
-MSG="$HOSTNAME UPS $1 Power Failure !!!"
-#
-(
-   echo "$MSG"
-   echo " "
-   /sbin/apcaccess status
-) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
+NOTIFY_HOST="ntfy.sh"
+NOTIFY_TOPIC=your-own-topic
+
+haveCurl=$(which curl)
+
+if [ $? -ne 0 ]; then
+  echo "Curl is not installed or not found in path, please install curl."
+  exit 1
+fi
+
+curl \
+  -s \
+  -o /dev/null \
+  -H "Title: $HOSTNAME UPS $1 Power Failure" \
+  -H "Priority: high" \
+  -H "Tags: ups" \
+  -d "$HOSTNAME UPS $1 has switched to battery power" $NOTIFY_HOST/$NOTIFY_TOPIC
+
 exit 0
